FROM node:18-alpine

WORKDIR /app

# Copy root package.json
COPY package*.json ./

# Copy backend
COPY backend ./backend

# Install dependencies
WORKDIR /app/backend
RUN npm install

# Generate Prisma client
RUN npx prisma generate

# Build
RUN npm run build

EXPOSE 3001

CMD ["npm", "start"]
